### ISSUE TITLE
INVALID ARGUMENT 

### ISSUE THREAD

**Issue by TentacleSama4254** [holodata/masterchat#2]
I tried the example you provided gives the same error
![IMG_20210628_225817](https://user-images.githubusercontent.com/74726248/123678755-59cf0200-d864-11eb-9bff-a4c07515f3a9.jpg)

**Comment by uetchy** [comment]
Are you trying to fetch reply chat? If so, set `isReplyChat` true:

https://github.com/holodata/masterchat/blob/9280689e76aa1e4e6578523ac5292f72c67bc842/packages/core/src/chat.ts#L889-L892

**Comment by uetchy** [comment]
But a clearer error message would certainly be better.

**Comment by TentacleSama4254** [comment]
could you give an example on hw to fetc livechats for a certain ideo iid at a cirtain time? would help a lot thx

**Comment by uetchy** [comment]
Just released a new version with a whole bunch of breaking changes and improvements.
I also wrote some example codes in the README please check it out.
https://github.com/holodata/masterchat

Fetching chat at a certain time of the video is not supported and I don't know how. Please consider sending PR if are interested!
