### ISSUE TITLE
[Question] Reason for large delay?

### ISSUE THREAD

**Issue by HughBone** [holodata/masterchat#5]
This works flawlessly but I was wondering why the timeout is so long between messages? I manually set the delay to 1 second and it seems to work fine.

`
if (this.isLive ?? true) {
    const timeoutMs = continuation.timeoutMs;
    await delay(1000, signal);
}
`

**Comment by RiceCakess** [comment]
YouTube API response contains a timeoutMs as guidance for the clients next requests, and messages are served in chunks by a time range which keeps things in sync. This follows the exact same behavior as the native Youtube client for a live stream, and avoids risk of soft ban

**Comment by HughBone** [comment]
Ahh I see, thanks
