### ISSUE TITLE
How to set the token acquired by extra/credential-fetcher into Masterchat?

### ISSUE THREAD

**Issue by ronnieeeeee** [holodata/masterchat#6]
How to set the token acquired by [extra\/credential-fetcher](https://github.com/holodata/masterchat/tree/master/extra/credential-fetcher) into Masterchat?

```typescript
const credentialsB64 =  token_acquired_by_credential_fetcher;

const credentials = credentialsB64
  ? JSON.parse(Buffer.from(credentialsB64, "base64").toString())
  : undefined;

await Masterchat.init(id!, { credentials });
```
Is it okay to look like this?

I referenced this [url](https://github.com/holodata/masterchat/blob/master/tests/message/message.test.ts).

**Comment by uetchy** [comment]
You can just pass base64 encoded string to Masterchat:

https://holodata.github.io/masterchat/interfaces/MasterchatOptions.html#credentials

```ts
const credentials = token_acquired_by_credential_fetcher;

await Masterchat.init(id, { credentials });
```

**Comment by ronnieeeeee** [comment]
Hello, thank you for your reply😄
I made a PR about what you taught me. https://github.com/holodata/masterchat/pull/8

**Comment by uetchy** [comment]
Thanks👍
